-- ============================================================================
-- GuideUp — stato delle policy e delle funzioni del database
--
-- Questo file era una proposta. Dal 18/09/2026 è un registro: le correzioni
-- sono state applicate al progetto `advplus-monitor-prod` e verificate
-- impersonando i tre ruoli sui dati reali. In fondo resta l'elenco di ciò che
-- non è ancora stato fatto.
--
-- Migrazioni, nell'ordine in cui sono state applicate:
--   1. chiude_accesso_anonimo_reminders_e_viste
--   2. handle_user_created_non_si_fida_del_ruolo_dal_client
--   3. fase1_funzioni_riparate_e_una_policy_per_comando
--   4. can_access_lead_non_nasconde_lo_storico_dei_disattivati
--   5. pulizia_colonne_e_funzioni_inutilizzate
-- ============================================================================


-- ============================================================================
-- 1. ACCESSO ANONIMO — chiuso
--
-- Con la chiave anon, quella pubblica dentro il bundle JavaScript, e senza
-- alcun login uscivano 16 promemoria e tutte le viste v_* con appuntamenti,
-- contratti e produzione per advisor. Su `reminders` anon aveva anche INSERT,
-- UPDATE, DELETE e TRUNCATE.
--
-- Cause: reminders aveva le RLS mai accese e zero policy; le dieci viste
-- appartengono a postgres, non hanno security_invoker e avevano SELECT
-- concesso ad anon.
--
-- Fatto: RLS accese su reminders con quattro policy, REVOKE ALL per anon su
-- reminders, REVOKE SELECT per anon sulle dieci viste.
-- Verificato: ogni chiamata anonima risponde 401, cancellazione compresa.
-- ============================================================================


-- ============================================================================
-- 2. ESCALATION DI PRIVILEGI — chiusa
--
-- disable_signup era false e il trigger on_auth_user_created chiamava
-- handle_user_created(), SECURITY DEFINER, che creava il profilo advisor
-- leggendo il ruolo da raw_user_meta_data, cioè dai metadati forniti dal
-- client alla registrazione. Chiunque poteva iscriversi dichiarandosi 'Admin'
-- e prendere il controllo dell'applicazione.
--
-- Fatto: il trigger ora collega soltanto l'utente auth al profilo già creato
-- dall'amministratore (UPDATE su user_id, email confrontata in minuscolo).
-- Non crea profili e non legge il ruolo dal client. Revocato EXECUTE ad anon,
-- authenticated e PUBLIC.
--
-- ANCORA DA FARE A MANO — non automatizzabile dal connettore:
--   Supabase → Authentication → Sign In / Providers → Email
--   → disattivare "Allow new users to sign up".
-- ============================================================================


-- ============================================================================
-- 3. FUNZIONI — riparate
--
-- Stato precedente:
--   is_admin()          leggeva da public.users, che è VUOTA: restituiva
--                       sempre false, per chiunque. Conseguenza concreta: un
--                       Admin non riusciva a salvare gli obiettivi di nessuno.
--   can_access_lead()   cercava il team con j.id = leads.owner_id e
--                       j.team_lead_id, due colonne mai valorizzate (0 righe
--                       su 7): il ramo Team Lead era cieco.
--   current_user_role() confrontava le email senza normalizzarle.
--
-- Ora tutte e tre hanno SET search_path TO 'public' e una sola convenzione: il
-- ruolo sta in advisors, il team in team_lead_user_id, leads.owner_id contiene
-- advisors.user_id (verificato: 457 lead su 457).
--
-- Nota su can_access_lead(): il ramo del Team Lead NON filtra sugli advisor
-- attivi. Disattivare un utente toglie l'accesso a lui, non deve nascondere il
-- suo lavoro a chi lo coordina — è quello che promette l'interfaccia quando si
-- disattiva un profilo. Una prima versione filtrava, e con un Junior
-- disattivato il suo Team Lead vedeva i lead ma non i contatti collegati.
-- ============================================================================


-- ============================================================================
-- 4. POLICY — una per tabella e per comando
--
-- Erano una settantina, con duplicati che si sommavano in OR annullandosi a
-- vicenda: le p_*_owner concedevano a QUALSIASI Team Lead di modificare e
-- cancellare i dati di QUALSIASI team. Ora sono 39.
--
--   leads                        is_admin() OR proprietario OR team
--   activities, appointments,    can_access_lead(lead_id)
--   proposals, contracts
--   reminders                    can_access_lead(lead_id) OR created_by
--   advisors                     lettura a tutti gli autenticati (serve
--                                all'interfaccia per gli assegnatari),
--                                scrittura solo Admin, più
--                                advisors_set_user_id_once per il primo accesso
--   goals, goals_monthly         lettura: Admin, sé stessi, il proprio team
--                                scrittura: Admin o Team Lead sul proprio Junior
--   import_logs                  scrive solo l'autore, legge l'autore o
--                                l'Admin, nessuna UPDATE né DELETE
--
-- VERIFICATO impersonando i ruoli sui dati veri (457 lead, 342 contatti,
-- 123 appuntamenti, 9 proposte, 27 contratti, 16 promemoria, 54 obiettivi):
--   Admin       vede tutto, is_admin() = true
--   Team Lead   vede tutto il proprio team, is_admin() = false
--   Junior      vede i propri 90 lead e ZERO altrui, i propri 12 obiettivi e
--               zero altrui
-- ============================================================================


-- ============================================================================
-- 5. PULIZIA — fatta
--
-- Funzioni eliminate, non citate da nessuna policy, vista o altra funzione:
--   lead_visible(), current_advisor_id(), is_team_lead()
--
-- Colonne eliminate, verificate riga per riga come vuote o costanti e nessuna
-- referenziata da viste:
--   activities.note, proposals.note      (si è sempre scritto `notes`)
--   appointments.method                  (la modalità sta in `mode`)
--   contracts.kind                       (il tipo sta in `contract_type`)
--   leads.status                         (valeva 'New' su tutte e 457 le righe)
--   leads.stop_working                   (false ovunque, contrario di is_working)
--   advisors.reports_to, team_lead_id    (0 righe valorizzate)
--   advisors.region                      (sempre nulla)
--
-- contracts.premium_annual allineata ad `amount` sui 27 contratti storici: la
-- colonna è NOT NULL con default a zero e non era mai stata usata, mentre il
-- valore vero sta in `amount`, che è quello letto da v_progress_monthly. Ora le
-- due somme coincidono (6.959,24 €).
-- ============================================================================


-- ============================================================================
-- QUELLO CHE RESTA DA FARE
-- ============================================================================

-- --------------------------------------------------------------------------
-- A. Viste SECURITY DEFINER   (l'advisor di Supabase lo segnala come ERROR)
--
-- Le dieci viste v_* girano come `postgres` e scavalcano le RLS delle tabelle
-- sottostanti. Ad anon non sono più esposte, ma un utente autenticato che le
-- interroghi direttamente vede i numeri di tutta la rete.
--
-- Ora che is_admin() funziona si può chiudere. Una per volta, controllando
-- dopo ognuna che Report, Dashboard e Obiettivi mostrino i dati giusti per un
-- Admin, un Team Lead e un Junior:
--
--   ALTER VIEW public.v_progress_monthly SET (security_invoker = on);
--   ALTER VIEW public.v_progress_annual  SET (security_invoker = on);
--   ALTER VIEW public.v_goals_monthly    SET (security_invoker = on);
--   ...
--
-- v_progress_monthly è quella che conta: la usano Dashboard, Report e
-- Obiettivi. Le altre non sono referenziate dall'applicazione attuale.

-- --------------------------------------------------------------------------
-- B. Colonne residue trattenute da viste
--
--   appointments.note, appointments.place      → v_month_key_appointments
--   contracts.company, contracts.policy_number → v_month_key_contracts
--   goals.month, consulenze, contratti,
--     prod_danni, prod_vprot, prod_vpr, prod_vpu → v_goals_monthly
--   goals_monthly.appuntamenti                 → v_goals_unificata
--   goals_monthly.consulenze, contratti, danni_non_auto, vita_protection,
--     vita_ricorrenti, vita_unici, ym          → sei viste
--
-- Nessuna di queste viste è usata dall'applicazione. Prima di eliminare le
-- colonne va deciso se servano a qualcuno per interrogazioni manuali.

-- --------------------------------------------------------------------------
-- C. Tabelle di altri prodotti
--
--   public.users            0 righe, RLS attiva senza policy
--   public.team_presences   0 righe, due policy di UPDATE sovrapposte
--   public.goals_annual     0 righe, solo policy di SELECT, usa advisor_id
--                           invece di advisor_user_id. Referenziata da
--                           v_team_goals_annual_sum e dalla variante _app:
--                           vanno eliminate insieme.
--
-- Nessuna è usata da GuideUp. Non le ho toccate: eliminare tabelle è
-- irreversibile e non è chiaro se appartengano a un altro applicativo.

-- --------------------------------------------------------------------------
-- D. Impostazioni di Auth (dashboard, non SQL)
--
--   [ ] Authentication → Sign In / Providers → Email:
--       disattivare "Allow new users to sign up"
--   [ ] Authentication → Policies:
--       attivare "Leaked password protection"

-- --------------------------------------------------------------------------
-- E. Colonne nuove per l'interfaccia — vedi docs/migrazioni.sql
--
-- Tre migrazioni già scritte e pronte, con il relativo ripristino:
--   1. appointments.outcome  (fatto / non presentato / annullato)
--   2. proposals.outcome     (in attesa / accettata / rifiutata)
--   3. activities.channel    estensione a whatsapp e sms
--
-- L'interfaccia funziona anche prima che vengano applicate: i campi che
-- dipendono da una colonna assente si disattivano da soli.

-- --------------------------------------------------------------------------
-- F. Flag contraddittori su advisors
--
-- `is_active` e `disabled` dicono la stessa cosa al contrario e sono già in
-- contraddizione: un Junior ha is_active = true e disabled = true insieme.
-- L'applicazione considera attivo solo chi ha is_active diverso da false E
-- disabled diverso da true. Andrebbe tenuto un flag solo.


-- ============================================================================
-- COME TORNARE INDIETRO
--
-- Le funzioni nella versione di partenza:
--
--   CREATE OR REPLACE FUNCTION public.is_admin()
--   RETURNS boolean LANGUAGE sql STABLE AS $function$
--     select exists (select 1 from public.users u
--                    where u.id = auth.uid() and lower(u.role) = 'admin');
--   $function$;
--
--   CREATE OR REPLACE FUNCTION public.current_user_role()
--   RETURNS text LANGUAGE sql STABLE AS $function$
--     select role from public.advisors where email = auth.jwt() ->> 'email' limit 1
--   $function$;
--
--   CREATE OR REPLACE FUNCTION public.can_access_lead(p_lead_id uuid)
--   RETURNS boolean LANGUAGE sql STABLE AS $function$
--     WITH l AS (SELECT owner_id FROM public.leads WHERE id = p_lead_id)
--     SELECT public.is_admin()
--       OR EXISTS (SELECT 1 FROM l WHERE owner_id = auth.uid())
--       OR EXISTS (SELECT 1 FROM l JOIN public.advisors j ON j.id = l.owner_id
--                  WHERE j.team_lead_id = auth.uid());
--   $function$;
--
-- Il trigger:
--
--   CREATE OR REPLACE FUNCTION public.handle_user_created()
--   RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
--   AS $function$
--   declare v_role text := coalesce(new.raw_user_meta_data->>'role', 'Junior');
--   begin
--     insert into public.advisors (user_id, email, role) values (new.id, new.email, v_role)
--     on conflict (email) do update
--       set user_id = excluded.user_id, role = coalesce(excluded.role, public.advisors.role);
--     return new;
--   end; $function$;
--
-- L'allineamento di premium_annual:  UPDATE public.contracts SET premium_annual = 0;
--
-- Colonne e policy eliminate sono ricostruibili dalla cronologia delle
-- migrazioni in Supabase. Prima di qualunque ripristino: Database → Backups.
-- ============================================================================
